name: "Build & Publish"

on:
  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
      domain:
        required: true
        type: string

env:
  registry: ghcr.io
  docker_image: ghcr.io/lyrecomanagement/apps/${{ inputs.domain }}/dev/${{ inputs.artifactId }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "git_short_sha=$calculatedSha" >> $GITHUB_ENV

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.registry}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push the Docker image
      run: |
        docker build . --file Dockerfile --tag $docker_image:$git_short_sha
        docker push $docker_image:$git_short_sha


