name: Maven Build
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      packages: write
      contents: read
    uses: LyrecoManagement/workflows/.github/workflows/maven-dev.yml@main
    with:
      artifactId: <artifactId>
      domain: <domain>
